### ISSUE TITLE
Is this project maintained?

### ISSUE THREAD

**Issue by Hakky54** [mhrimaz/AwesomeJavaFX#122]
Hi @mhrimaz 

I noticed the project has not been updated since August 2022. Do you need any maintainers? I would like to volunteer if you are ok.

**Comment by mhrimaz** [comment]
@Hakky54 Thanks for showing interest. You can always contribute by making a pull request. Unfortunately I am not actively working on JavaFX. And I am not also sure if maintaining this repo is helpful anymore or not (https://www.jfx-central.com/home).

If you really want to do it, I can also add you as the maintainer.

**Comment by AlmasB** [comment]
@Hakky54 Hi Hakan, thanks for the offer to help.

Jfx-central is the latest and currently active iteration of all things JavaFX. The user-facing website is essentially the spiritual successor of this repository. It is maintained by Dirk. Github link: https://github.com/dlemmermann/jfxcentral

@mhrimaz is right. If you wish to contribute JavaFX resources, then effort-wise contributing to jfx-central would be more productive for the community.

I suspect there are a lot of good projects in this repo that have not made their way to jfx-central yet, so that would be a good place to start. Though some curation is needed since some projects may not exist or are not relevant/active anymore.

We may also wish to have a link to jfx-central at the top of the README file to redirect new developers...

**Comment by Hakky54** [comment]
Ah, I see. Now it makes more sense. I still see value in the awesome javafx list. It is simple, straigt forward and curated list of projects and other related stuff. The markdown template makes it easy for others to just scan through the content. I prefer to use this repo, but it would be a good idea to sync in both places.

Let's see how it works out. I will maintain with the help of other developers who want to contribute.
